apiVersion: argoproj.io/v1
kind: Application
metadata:
  name: wordpress-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: git@github.com:ravi-pandit/k8s-wordpress.git
    targetRevision: HEAD
    path: manifest/wordpress-apache2
  destination: 
    server: https://kubernetes.default.svc
    namespace: apache

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
