apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-apache-configmap
  namespace: apache
data:
  # WordPress configuration options
  WP_DEBUG: "false"
  WP_DEBUG_LOG: "false"
  WP_DEBUG_DISPLAY: "false"
  WP_CACHE: "true"
  # Database configuration options
  WORDPRESS_DB_NAME: wordpressk8s
  WORDPRESS_DB_USER: admin
  WORDPRESS_DB_PASSWORD: LIW43hlnlZVrDB^S
  WORDPRESS_DB_HOST: terraform-laravelk8s-1.c685olbnapdz.ap-south-1.rds.amazonaws.com:3306
  WORDPRESS_DB_CHARSET: utf8mb4
  WORDPRESS_DB_COLLATE: ""

  # Security keys
  # WORDPRESS_AUTH_KEY: oZpOr$?d|oJ$F?fo-GsEL%--V[=kM3;/==kYA6D .!8Tw3B36bXr_W|+OI7|`GNZ
  # WORDPRESS_SECURE_AUTH_KEY: (+,qi4*s~nF<3G;Th(+6l0 T`hCYFPQY;-q^?(&{2_!<Bw`a3pZA1=/HHMvC3R47
  # WORDPRESS_LOGGED_IN_KEY: Py4,lV|{N_mg^p|7R@=.7|-w&u_{dPLZ|s|fs#}-:-!CdC/GW7e+{lH>eL.tQi7`
  # WORDPRESS_NONCE_KEY: T[(q>xwTO[};p=[Z=yf?t:DfCl=EQBL[BY2Hs|g6`%qxIo>ARo(9JIL8-$yYw$G,
  # WORDPRESS_AUTH_SALT: o^T~>[hg KD$ K.E@5FD+YVYN0hYN2)E#KTgI.`l}9DCd#Xd a.f]33%2BASn$`n
  # WORDPRESS_SECURE_AUTH_SALT: _p9l$Q5gh>L^TD,)0^;U=03oW%(li5:(i+OX,Fq+l^(dwP6wmVf? S]67:/AGe,)
  # WORDPRESS_LOGGED_IN_SALT: "-rGd6D7K-cpDpNFaQW6c^uw&EQvSLI+ni=y]@i`i{y0#pnT,m_=LCLt8)6=//}+("
  # WORDPRESS_NONCE_SALT: {oeyw%H)}gA6ZWUO)^2-f,.hFTrEE-O},{l=x+y0Rlki+&YTZACJ(LF1@VUhU=h 
