apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets-manager
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: terraform-password-ig5CfLE49dKMFwek
        objectType: secretsmanag
        keyList:
          - keyName: password
            envName: DB_PASSWORD


# apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
# kind: SecretProviderClass
# metadata:
#   name: aws-secrets-manager
# spec:
#   provider: aws
#   parameters:
#     objects: |
#       - objectName: <aws-secret-name>
#         objectType: secretsmanager
#         keyList:
#           - keyName: username
#             envName: DB_USERNAME
#           - keyName: password
#             envName: DB_PASSWORD