# kind: PersistentVolume
# apiVersion: v1
# metadata:
#   name: ebs-claim
#   labels:
#     type: local
# spec:
#   storageClassName: ebs-sc
#   capacity:
#     storage: 4Gi
#   local:
#     path: /data
#   persistentVolumeReclaimPolicy: Retain
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: ebs-sc
#   nodeAffinity:
#     required:
#       nodeSelectorTerms:
#         - matchExpressions:
#           - key: app
#             operator: In
#             values:
#               - wordpress-site

# PersistentVolumeClaim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 6Gi

# PersistentVolumeClaim
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: pvc-csi
# spec:
#   accessModes:
#   - ReadWriteOnce
#   storageClassName: gp2
#   resources:
#     requests:
#       storage: 4Gi


# # PersistentVolumeClaim
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: ebs-mysql-pv-claim
# spec: 
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: ebs-sc
#   resources: 
#     requests:
#       storage: 4Gi