kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata: 
  name: ebs-sc
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp2

# gp3 
# kind: StorageClass
# apiVersion: storage.k8s.io/v1
# metadata:
#   name: gp3
# allowVolumeExpansion: true
# provisioner: ebs.csi.aws.com
# volumeBindingMode: WaitForFirstConsumer
# parameters:
#   type: gp3