name: Deploy to EKS
on:
  push:
    # paths:
    # - wordpress-fpm/**
    branches: [ main ]

env:
  ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION}}.amazonaws.com
  ECR_REPOSITORY: wordpress
  AWS_DEFAULT_OUTPUT: json
  VERSION: ${{ ${{ github.sha }} | cut -c1-7 }}

jobs:
  
  Build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Set short SHA environment variable
      #   run: echo "export DOCKER_SHORT_SHA=${GITHUB_SHA:0:7}" >> $GITHUB_ENV

      # Build docker image
      - name: Build Docker image
        id: build-image
        run: |
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          # Use Docker `latest` tag convention
          [ "$VERSION" == "main" ] && VERSION=$(echo ${{ github.sha }} | cut -c1-7)
          # echo "::set-output name=version::$VERSION"
          # echo "::version::$VERSION"
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          cd wordpress-fpm
          echo "$VERSION", "$GITHUB_OUTPUT"
          #docker build -t ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:$VERSION .

      - name: echo version
        id: echo
        run : echo "$VERSION"